import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter_svg/svg.dart';
import 'package:anak_hebat/core.dart';

Future<void> loadImage() async {
  WidgetsBinding.instance.addPostFrameCallback((_) async {
    final context = Get.navigatorKey.currentContext;
    if (context == null) return;

    try {
      final allAssets = <String>[
        MediaRes.images.login,
        MediaRes.images.anak,
        MediaRes.images.benar,
        MediaRes.images.coin,
        MediaRes.images.salah,
        MediaRes.images.silang,
        MediaRes.images.star,
        MediaRes.images.gold,
        MediaRes.images.silver,
        MediaRes.images.bronze,
        MediaRes.images.leaderboard,
        MediaRes.images.lingkaran,
        MediaRes.images.persegiPanjang,
        MediaRes.images.persegi,
        MediaRes.images.segitiga,
        MediaRes.images.diatasMeja,
        MediaRes.images.dibawahMeja,
        MediaRes.images.disampingMeja,
        MediaRes.images.buahNaga,
        MediaRes.images.kupuKupu,
        MediaRes.images.wortel1,
        MediaRes.images.wortel2,
        MediaRes.background.kelas,
        MediaRes.background.outside,
        MediaRes.background.leaderboard,
        MediaRes.background.berhitung,
        MediaRes.background.mencocokanAngka,
        MediaRes.background.mengenalPosisi,
        MediaRes.background.perbandingan1,
        MediaRes.background.perbandingan2,
        MediaRes.background.perbandingan3,
        MediaRes.button.back,
        MediaRes.button.dashboard,
        MediaRes.button.home,
        MediaRes.button.keluar,
        MediaRes.button.kembali,
        MediaRes.button.next,
        MediaRes.button.retry,
        MediaRes.button.speakerOn,
        MediaRes.button.speakerOff,
        MediaRes.button.tandaSeru,
        MediaRes.button.belajar,
        MediaRes.button.belajarAngka,
        MediaRes.button.belajarHuruf,
        MediaRes.button.quiz,
        MediaRes.button.quizAngka,
        MediaRes.button.quizHuruf,
        MediaRes.button.mencocokanAngka,
        MediaRes.button.mengenalAngka,
        MediaRes.button.quizLiterasi,
        MediaRes.button.quizNumerasi,
        MediaRes.button.mengenalBentuk,
        MediaRes.button.mengenalPerbandingan,
        MediaRes.button.mengenalPosisi,
        MediaRes.button.mengenalPosisiUrutan,
        MediaRes.button.berhitung,
        MediaRes.button.mengenalAngkaBenda,
        MediaRes.logo.logo,
        MediaRes.materi.a,
        MediaRes.materi.b,
        MediaRes.materi.c,
        MediaRes.materi.d,
        MediaRes.materi.e,
        MediaRes.materi.f,
        MediaRes.materi.g,
        MediaRes.materi.h,
        MediaRes.materi.i,
        MediaRes.materi.j,
        MediaRes.materi.k,
        MediaRes.materi.l,
        MediaRes.materi.m,
        MediaRes.materi.n,
        MediaRes.materi.o,
        MediaRes.materi.p,
        MediaRes.materi.q,
        MediaRes.materi.r,
        MediaRes.materi.s,
        MediaRes.materi.t,
        MediaRes.materi.u,
        MediaRes.materi.v,
        MediaRes.materi.w,
        MediaRes.materi.x,
        MediaRes.materi.y,
        MediaRes.materi.z,
        MediaRes.quiz.literasi.jawaban1A,
        MediaRes.quiz.literasi.jawaban1B,
        MediaRes.quiz.literasi.jawaban1C,
        MediaRes.quiz.literasi.jawaban2A,
        MediaRes.quiz.literasi.jawaban2B,
        MediaRes.quiz.literasi.jawaban2C,
        MediaRes.quiz.literasi.jawaban3A,
        MediaRes.quiz.literasi.jawaban3B,
        MediaRes.quiz.literasi.jawaban3C,
        MediaRes.quiz.literasi.jawaban4A,
        MediaRes.quiz.literasi.jawaban4B,
        MediaRes.quiz.literasi.jawaban4C,
        MediaRes.quiz.literasi.jawaban5A,
        MediaRes.quiz.literasi.jawaban5B,
        MediaRes.quiz.literasi.jawaban5C,
        MediaRes.quiz.literasi.jawaban6A,
        MediaRes.quiz.literasi.jawaban6B,
        MediaRes.quiz.literasi.jawaban6C,
        MediaRes.quiz.literasi.jawaban7A,
        MediaRes.quiz.literasi.jawaban7B,
        MediaRes.quiz.literasi.jawaban7C,
        MediaRes.quiz.literasi.jawaban8A,
        MediaRes.quiz.literasi.jawaban8B,
        MediaRes.quiz.literasi.jawaban8C,
        MediaRes.quiz.literasi.jawaban9A,
        MediaRes.quiz.literasi.jawaban9B,
        MediaRes.quiz.literasi.jawaban9C,
        MediaRes.quiz.literasi.jawaban10A,
        MediaRes.quiz.literasi.jawaban10B,
        MediaRes.quiz.literasi.jawaban10C,
        MediaRes.quiz.numerasi.jawaban1A,
        MediaRes.quiz.numerasi.jawaban1B,
        MediaRes.quiz.numerasi.jawaban2A,
        MediaRes.quiz.numerasi.jawaban2B,
        MediaRes.quiz.numerasi.jawaban2C,
        MediaRes.quiz.numerasi.jawaban3A,
        MediaRes.quiz.numerasi.jawaban3B,
        MediaRes.quiz.numerasi.jawaban3C,
        MediaRes.quiz.numerasi.jawaban4A,
        MediaRes.quiz.numerasi.jawaban4B,
        MediaRes.quiz.numerasi.jawaban4C,
        MediaRes.quiz.numerasi.jawaban5A,
        MediaRes.quiz.numerasi.jawaban5B,
        MediaRes.quiz.numerasi.jawaban5C,
        MediaRes.quiz.numerasi.jawaban6A,
        MediaRes.quiz.numerasi.jawaban6B,
        MediaRes.quiz.numerasi.jawaban7A,
        MediaRes.quiz.numerasi.jawaban7B,
        MediaRes.quiz.numerasi.jawaban7C,
        MediaRes.quiz.numerasi.jawaban8A,
        MediaRes.quiz.numerasi.jawaban8B,
        MediaRes.quiz.numerasi.jawaban8C,
        MediaRes.quiz.numerasi.jawaban10A,
        MediaRes.quiz.numerasi.jawaban10B,
        MediaRes.quiz.numerasi.jawaban10C,
        MediaRes.quiz.numerasi.soal1,
        MediaRes.quiz.numerasi.soal2,
        MediaRes.quiz.numerasi.soal3,
        MediaRes.quiz.numerasi.soal4,
        MediaRes.quiz.numerasi.soal5,
        MediaRes.quiz.numerasi.soal6A,
        MediaRes.quiz.numerasi.soal6B,
      ];

      final rasterImages =
          allAssets.where((path) => path.endsWith('.png') || path.endsWith('.jpg')).toList();
      final svgImages = allAssets.where((path) => path.endsWith('.svg')).toList();

      // Precache raster (PNG/JPG)
      for (final path in rasterImages) {
        await precacheImage(AssetImage(path), context);
      }

      // Precache SVG
      for (final path in svgImages) {
        final loader = SvgAssetLoader(path);
        await svg.cache.putIfAbsent(loader.cacheKey(null), () => loader.loadBytes(null));
      }
    } catch (e) {
      debugPrint('Error preloading assets: $e');
    }
  });
}
